[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
startCommand = "npm start"

[environments.production.variables]
NODE_ENV = "production"