[build]
builder = "NIXPACKS"

# Backend service configuration
[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
NODE_ENV = "production"